[build-system]
requires = ["scikit-build-core"]
build-backend = "scikit_build_core.build"

[project]
name = "cuda_op"
version = "0.0.1"

[tool.scikit-build]
build-dir = "build"
cmake.build-type = "Release"

