name: CI CPP on Ubuntu 24.04
on:
  pull_request:
    branches: [master]
    paths: 'cpp/**'

jobs:
  build-tests:
    name: "cpp-ubuntu-24.04-${{ matrix.compiler }}-${{ matrix.version }}"
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - { compiler: "gcc",   version: "14.2.0" }
          - { compiler: "clang", version: "18.1.3" }

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup C/C++ Environment
        run: |
          set -euo pipefail
          major=$(echo ${{ matrix.version }} | cut -d'.' -f1)
          if [[ "${{ matrix.compiler }}" == "clang" ]]; then
            echo "CC=clang-${major}" >> ${GITHUB_ENV}
            echo "CXX=clang++-${major}" >> ${GITHUB_ENV}
          else
            echo "CC=gcc-${major}" >> ${GITHUB_ENV}
            echo "CXX=g++-${major}" >> ${GITHUB_ENV}
          fi
      - name: Install Common Dependency
        run: |
          sudo apt-get install -y ninja-build
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            multithreads_read_same_file: 'cpp/general/multithreads_read_same_file/**'
            memory_leak: 'cpp/general/memory_leak_detector/**'
            example: 'cpp/bench/example/**'
            memory_allocation: 'cpp/bench/memory_allocation/**'
            char_classifier: 'cpp/bench/char_classifier/**'

      - name: Run multithreads_read_same_file
        if: steps.filter.outputs.multithreads_read_same_file == 'true'
        run: |
          set -euo pipefail
          sudo apt-get install -y libboost-all-dev
          cd cpp/general/multithreads_read_same_file/
          cmake -S . -B build -GNinja
          cmake --build build -v -j`nproc`
          ./build/main

      - name: Use valgrind to check memory_leak
        if: steps.filter.outputs.memory_leak == 'true'
        run: |
          set -euo pipefail
          sudo apt-get install -y valgrind
          cd cpp/general/memory_leak_detector/
          cmake -S . -B build -GNinja
          cmake --build build -v -j`nproc`
          if valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes --error-exitcode=1 ./build/memory_leak; then
            echo "memory leak should be detected" && exit 1
          fi
          valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes --error-exitcode=1 ./build/safely_allocate_memory

      - name: Use ASan to check memory_leak
        if: steps.filter.outputs.memory_leak == 'true'
        run: |
          set -euo pipefail
          rm -rf build
          cd cpp/general/memory_leak_detector/
          cmake -S . -B build -GNinja -DENABLE_ASAN=on
          cmake --build build -v -j`nproc`
          if ./build/memory_leak; then
            echo "memory leak should be detected" && exit 1
          fi
          ./build/safely_allocate_memory

      - name: Run example
        if: steps.filter.outputs.example == 'true'
        run: |
          set -euo pipefail
          cd cpp/bench/example/
          cmake -S . -B build -GNinja
          cmake --build build -v -j`nproc`
          ./build/example

      - name: Run memory_allocation
        if: steps.filter.outputs.memory_allocation == 'true'
        run: |
          set -euo pipefail
          cd cpp/bench/memory_allocation/
          cmake -S . -B build -GNinja
          cmake --build build -v -j`nproc`
          ./build/memory_allocation

      - name: Run char_classifier
        if: steps.filter.outputs.char_classifier == 'true'
        run: |
          set -euo pipefail
          cd cpp/bench/char_classifier/
          cmake -S . -B build -GNinja
          cmake --build build -v -j`nproc`
          ./build/char_classifier
